'use client';

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { ChartContainer } from "@/components/ui/chart";
import { Bar, BarChart, CartesianGrid, XAxis, YAxis } from "recharts";
import type { ChartConfig } from "@/components/ui/chart";

const chartData = [
  { category: "Gate Blocks", count: 12, fill: "var(--color-chart-1)" },
  { category: "Load Coach", count: 8, fill: "var(--color-chart-2)" },
  { category: "Fatigue Esc.", count: 3, fill: "var(--color-chart-3)" },
  { category: "Road Rework", count: 5, fill: "var(--color-chart-4)" },
  { category: "Security", count: 7, fill: "var(--color-chart-5)" },
];

const chartConfig = {
  count: {
    label: "Actions",
  },
  "Gate Blocks": { label: "Gate Blocks", color: "hsl(var(--chart-1))" },
  "Load Coach": { label: "Load Coach", color: "hsl(var(--chart-2))" },
  "Fatigue Esc.": { label: "Fatigue Esc.", color: "hsl(var(--chart-3))" },
  "Road Rework": { label: "Road Rework", color: "hsl(var(--chart-4))" },
  Security: { label: "Security", color: "hsl(var(--chart-5))" },
} satisfies ChartConfig;

export function AutomatedActionsCard() {
  return (
    <Card className="card-hover">
      <CardHeader>
        <CardTitle>Automated Actions Today</CardTitle>
        <CardDescription>Actions generated by the Smart Hub based on real-time data.</CardDescription>
      </CardHeader>
      <CardContent>
        <ChartContainer config={chartConfig} className="w-full h-48">
          <BarChart
            accessibilityLayer
            data={chartData}
            layout="vertical"
            margin={{ left: 10, top: 0, right: 10, bottom: 0 }}
          >
            <CartesianGrid horizontal={false} />
            <XAxis type="number" dataKey="count" hide />
            <YAxis
              dataKey="category"
              type="category"
              tickLine={false}
              axisLine={false}
              tick={{ fill: "hsl(var(--muted-foreground))", fontSize: 12 }}
              className="translate-x-[-10px]"
            />
            <Bar dataKey="count" layout="vertical" radius={5}>
            </Bar>
          </BarChart>
        </ChartContainer>
      </CardContent>
    </Card>
  );
}
